oak:
  ros__parameters:

    camera:
      i_pipeline_type: STEREO   # 0=RGB, 1=STEREO, 2=RGBD
      i_enable_imu: false

    stereo:
      i_enable: true
      i_publish_topic: true

      # depth quality
      i_align_depth: true
      i_lr_check: true
      i_subpixel: true
      i_confidence_threshold: 200

      # ðŸ”´ REQUIRED for PointCloud2
      i_publish_pointcloud: true
      i_pointcloud_fps: 10

    rgb:
      i_enable: true
      i_fps: 30

